/*
 * -----------------------------------------------------------------------
 *  File:          $Source:  $
 *  Version:       $Revision:  $
 *  Last Modified: $Date:  $
 * -----------------------------------------------------------------------
 *  Copyright (C) 2003 Keith Stribley <jungleglacier@snc.co.uk>
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 * -----------------------------------------------------------------------
 */

package languagetest.language.gui;

/**
 *
 * @author  keith
 */
public class ConversationEditorPanel extends javax.swing.JPanel
{
    private MainEditorPanel mainEditorPanel = null;
    
    /** Creates new form ConversationEditorPanel */
    public ConversationEditorPanel(MainEditorPanel mainEditorPanel)
    {
        this.mainEditorPanel = mainEditorPanel;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        speakerList = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        speakerName = new javax.swing.JTextField();
        addSpeaker = new javax.swing.JButton();
        renameSpeaker = new javax.swing.JButton();
        deleteSpeaker = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.TitledBorder("Conversation"));
        jPanel2.setLayout(new java.awt.BorderLayout(1, 0));

        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        jTextField1.setText("Conversation");
        jPanel3.add(jTextField1);

        jLabel4.setText("0");
        jPanel3.add(jLabel4);

        jLabel5.setText("0");
        jPanel3.add(jLabel5);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setText("Description:");
        jPanel1.add(jLabel1);

        jLabel2.setText("Number of Phrases:");
        jPanel1.add(jLabel2);

        jLabel3.setText("Number of Speakers:");
        jPanel1.add(jLabel3);

        jPanel2.add(jPanel1, java.awt.BorderLayout.WEST);

        add(jPanel2, java.awt.BorderLayout.NORTH);

        speakerList.setBorder(new javax.swing.border.TitledBorder("Speakers"));
        speakerList.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Question", "Answer" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        add(speakerList, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.GridLayout(0, 1));

        speakerName.setText("jTextField2");
        jPanel5.add(speakerName);

        addSpeaker.setText("Add speaker");
        jPanel5.add(addSpeaker);

        renameSpeaker.setText(" Rename Speaker");
        jPanel5.add(renameSpeaker);

        deleteSpeaker.setText("Delete Speaker");
        jPanel5.add(deleteSpeaker);

        jPanel4.add(jPanel5, java.awt.BorderLayout.NORTH);

        add(jPanel4, java.awt.BorderLayout.EAST);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton deleteSpeaker;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField speakerName;
    private javax.swing.JList speakerList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton renameSpeaker;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton addSpeaker;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
    
}
