/*
 * -----------------------------------------------------------------------
 *  File:          $Source: /home/keith/cvsroot/projects/LanguageAids/uk/co/dabsol/stribley/language/gui/FindDialog.java,v $
 *  Version:       $Revision: 1.2 $
 *  Last Modified: $Date: 2003/12/26 13:15:31 $
 * -----------------------------------------------------------------------
 *  Copyright (C) 2003 Keith Stribley <jungleglacier@snc.co.uk>
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 * -----------------------------------------------------------------------
 */

package languagetest.language.gui;

import java.awt.Font;
import java.awt.Rectangle;
import java.awt.Point;
import javax.swing.table.TableModel;
import javax.swing.JViewport;
import javax.swing.JOptionPane;
import languagetest.language.test.UserConfig;
import languagetest.language.test.LanguageConfig;
import languagetest.language.test.UniversalLanguage;

import languagetest.language.test.TestItem;
/**
 *
 * @author  Keith Stribley
 */
public class FindDialog extends javax.swing.JDialog
{
    /**
	 * 
	 */
	private static final long serialVersionUID = -5399786891975933646L;
	private VocabTablePanel vocabPanel = null;
    /** Creates new form FindDialog */
    public FindDialog(java.awt.Frame parent, boolean modal, 
                      VocabTablePanel panel)
    {
        super(parent, modal);
        initComponents();
        this.vocabPanel = panel;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        optionGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        findButton = new javax.swing.JButton();
        findBackwardsButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        nativeRadioButton = new javax.swing.JRadioButton();
        foreignRadioButton = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        searchText = new javax.swing.JTextArea();

        setTitle("Find Test Item");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        findButton.setText("Find");
        findButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                findButtonActionPerformed(evt);
            }
        });

        jPanel1.add(findButton);

        findBackwardsButton.setText("Find backwards");
        findBackwardsButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                findBackwardsButtonActionPerformed(evt);
            }
        });

        jPanel1.add(findBackwardsButton);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                closeButtonActionPerformed(evt);
            }
        });

        jPanel1.add(closeButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setBorder(new javax.swing.border.TitledBorder("Find Options"));
        nativeRadioButton.setSelected(true);
        nativeRadioButton.setText("Find in English");
        optionGroup.add(nativeRadioButton);
        nativeRadioButton.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                nativeRadioButtonItemStateChanged(evt);
            }
        });

        jPanel2.add(nativeRadioButton);

        foreignRadioButton.setText("Find in Burmese");
        optionGroup.add(foreignRadioButton);
        foreignRadioButton.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                foreignRadioButtonItemStateChanged(evt);
            }
        });

        jPanel2.add(foreignRadioButton);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(new javax.swing.border.TitledBorder("Search String"));
        searchText.setPreferredSize(new java.awt.Dimension(0, 32));
        jPanel3.add(searchText, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void foreignRadioButtonItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_foreignRadioButtonItemStateChanged
    {//GEN-HEADEREND:event_foreignRadioButtonItemStateChanged
        // Add your handling code here:
        setFindTextFont();
    }//GEN-LAST:event_foreignRadioButtonItemStateChanged

    private void nativeRadioButtonItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_nativeRadioButtonItemStateChanged
    {//GEN-HEADEREND:event_nativeRadioButtonItemStateChanged
        // Add your handling code here:
        setFindTextFont();
    }//GEN-LAST:event_nativeRadioButtonItemStateChanged

    private void setFindTextFont()
    {
        LanguageConfig lc = LanguageConfig.getCurrent();
        if (foreignRadioButton.isSelected())
        {
            UniversalLanguage ful = lc.getForeignLanguage();
            Font f = UserConfig.getCurrent().getForeignDefaultFont(ful);
            searchText.setFont(f);
        }
        else
        {
            UniversalLanguage nul = lc.getNativeLanguage();
            Font f = UserConfig.getCurrent().getNativeDefaultFont(nul);
            searchText.setFont(f);
        }
    }
    
    private void findButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_findButtonActionPerformed
    {//GEN-HEADEREND:event_findButtonActionPerformed
        // Add your handling code here:
        find(true);
        
    }//GEN-LAST:event_findButtonActionPerformed

    private void findBackwardsButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_findBackwardsButtonActionPerformed
    {//GEN-HEADEREND:event_findBackwardsButtonActionPerformed
        // Add your handling code here:
        find(false);
    }//GEN-LAST:event_findBackwardsButtonActionPerformed

    private void find(boolean direction)
    {
        //boolean wrapped = false;
        boolean found = false;
        int step = (direction) ? 1 : -1;
        int startRow = 0;
        int row = 0;
        int [] rows = vocabPanel.getTable().getSelectedRows();
        String testText = null;
        if (rows.length>0) startRow = rows[0];
        row = startRow + step;
        TableModel model = vocabPanel.getTable().getModel();
        if (row >= model.getRowCount()) row = 0;
        if (row < 0) row = model.getRowCount() - 1;
        do 
        {
            TestItem item = (TestItem)model.getValueAt(row, 0);
            if (nativeRadioButton.isSelected())
            {
                testText = item.getNativeText();
            }
            else
            {
                testText = item.getForeignText();
            }
            if (testText.indexOf(searchText.getText()) > -1)
            {
                found = true;
                vocabPanel.getTable().setRowSelectionInterval(row, row);
                JViewport viewport = vocabPanel.getScrollPane().getViewport();
                Rectangle visable = viewport.getViewRect();
                Point point = viewport.getViewPosition();
                int rowY = row * vocabPanel.getTable().getRowHeight();
                if (rowY > visable.getMaxY() || rowY < visable.getMinY())
                {
                    viewport.setViewPosition(new Point((int)point.getX(),rowY));
                }
                break;
            }
            row += step;
            if (row >= model.getRowCount()) 
            {
                row = 0;
                //wrapped = true;
            }
            if (row < 0) 
            {
                row = model.getRowCount() - 1;
                //wrapped = true;
            }
        } while (row != startRow);
        if (!found)
        {
            JOptionPane.showMessageDialog(this,"No occurances found","Find",
                                          JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeButtonActionPerformed
    {//GEN-HEADEREND:event_closeButtonActionPerformed
        // Add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt)
    {//GEN-FIRST:event_closeDialog
        setVisible(false);
    }//GEN-LAST:event_closeDialog
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea searchText;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton nativeRadioButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton findButton;
    private javax.swing.ButtonGroup optionGroup;
    private javax.swing.JButton findBackwardsButton;
    private javax.swing.JRadioButton foreignRadioButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton closeButton;
    // End of variables declaration//GEN-END:variables
    
}
