/*
 * LanguageChooser.java
 *
 * Created on April 17, 2004, 6:06 PM
 */

package languagetest.language.gui;

import java.awt.BorderLayout;
import org.jfree.ui.RefineryUtilities;
import languagetest.language.test.UniversalLanguage;

/**
 *
 * @author  keith
 */
public class LanguageChooser extends javax.swing.JDialog
{
    /**
	 * 
	 */
	private static final long serialVersionUID = -7151255355611832882L;
	private LanguagePanel langPanel = null;
    private boolean ok = false;
    /** Creates new form LanguageChooser */
    public LanguageChooser(java.awt.Frame parent, String title)
    {
        super(parent, true);
        langPanel = new LanguagePanel(title);        
        initComponents();
        this.getContentPane().add(langPanel, BorderLayout.WEST);
        this.setSize(600, 400);
        RefineryUtilities.centerDialogInParent(this);
    }
    
    /** Creates new form LanguageChooser */
    public LanguageChooser(java.awt.Dialog parent, String title)
    {
        super(parent, true);
        langPanel = new LanguagePanel(title);        
        initComponents();
        this.getContentPane().add(langPanel, BorderLayout.WEST);
        this.setSize(600, 400);
        RefineryUtilities.centerDialogInParent(this);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        helpScrollPane = new javax.swing.JScrollPane();
        helpArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });

        helpScrollPane.setViewportBorder(new javax.swing.border.TitledBorder("Help Tips"));
        helpArea.setEditable(false);
        helpArea.setLineWrap(true);
        helpArea.setRows(10);
        helpArea.setText("Specify a language. This dialog creates a code that uniquely identifies the language for use in your modules.\nOnly the Language field needs to be specified. If your language is not listed, then you should choose the closest language family and use the Variant field to specify the dialect. \nYou should only specify the Country if you want to specifically specify a dialect of your chosen language that is unique to a particular country.\nThe Variant is optional. You are free to type anything in the variant field, but it is important that you agree with fellow language learners a standard nomenclature, otherwise you will not be able to share modules.\nIf your language can use several different scripts or you want to use a Latin (Romanized) equivalent of an Asian script, then you should specify that as well.");
        helpArea.setWrapStyleWord(true);
        helpArea.setAlignmentX(0.0F);
        helpArea.setOpaque(false);
        helpScrollPane.setViewportView(helpArea);

        getContentPane().add(helpScrollPane, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                okButtonActionPerformed(evt);
            }
        });

        jPanel1.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel1.add(cancelButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
    {//GEN-HEADEREND:event_cancelButtonActionPerformed
        // Add your handling code here:
        ok = false;
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonActionPerformed
    {//GEN-HEADEREND:event_okButtonActionPerformed
        ok = true;
        this.setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt)//GEN-FIRST:event_closeDialog
    {
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    public UniversalLanguage getLanguage()
    {
        return langPanel.getLanguage();
    }
    
    public boolean isOk()
    {
        return ok;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        LanguageChooser chooser = new LanguageChooser(new javax.swing.JFrame(), "Test");
        chooser.setSize(500, 300);
        chooser.setVisible(true);
        System.out.println(chooser.getLanguage().getDescription());
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextArea helpArea;
    private javax.swing.JScrollPane helpScrollPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    
}
