/*
 * -----------------------------------------------------------------------
 *  File:          $Source: /home/keith/cvsroot/projects/LanguageAids/uk/co/dabsol/stribley/language/gui/ResultsPanel.java,v $
 *  Version:       $Revision: 1.9 $
 *  Last Modified: $Date: 2005/03/25 04:49:26 $
 * -----------------------------------------------------------------------
 *  Copyright (C) 2003 Keith Stribley <jungleglacier@snc.co.uk>
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 * -----------------------------------------------------------------------
 */

package languagetest.language.gui;

import java.text.DecimalFormat;
import java.util.Iterator;
import java.util.Date;
import javax.swing.JOptionPane;


import languagetest.language.test.UserConfig;
import languagetest.language.test.TestHistoryStorageException;
import languagetest.language.test.TestItem;
import languagetest.language.test.Test;

/**
 *
 * @author  keith
 */
public class ResultsPanel extends javax.swing.JPanel
{
    private MainFrame mainFrame = null;
    private Test lastTest = null;
    /** Creates new form ResultsPanel */
    public ResultsPanel(MainFrame mainFrame)
    {
        this.mainFrame = mainFrame;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        buttonPanel = new javax.swing.JPanel();
        editButton = new javax.swing.JButton();
        newTestButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        numPassedLabel = new javax.swing.JLabel();
        untestedLabel = new javax.swing.JLabel();
        totalNumTestsLabel = new javax.swing.JLabel();
        numRetestsLabel = new javax.swing.JLabel();
        percentFirstTimePassesLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        saveCheckBox = new javax.swing.JCheckBox();
        retestButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        editButton.setText("Edit Modules");
        editButton.setToolTipText("Open the Module Editor to create new Test Modules or modify existing ones.");
        editButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                editButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(editButton);

        newTestButton.setText("Back");
        newTestButton.setToolTipText("Back to main test selection screen.");
        newTestButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newTestButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(newTestButton);

        add(buttonPanel, java.awt.BorderLayout.SOUTH);

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleBackground"));
        jPanel2.setBorder(new javax.swing.border.EtchedBorder());
        titleLabel.setFont(new java.awt.Font("Dialog", 1, 18));
        titleLabel.setForeground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleForeground"));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Test Results");
        jPanel2.add(titleLabel);

        add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jPanel1.setBorder(new javax.swing.border.EtchedBorder());
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
        jLabel1.setText("Number of tests passed:");
        jPanel5.add(jLabel1);

        jLabel2.setText("Number untested:");
        jPanel5.add(jLabel2);

        jLabel3.setText("Total number of tests:");
        jPanel5.add(jLabel3);

        jLabel5.setText("Number of retests:");
        jPanel5.add(jLabel5);

        jLabel7.setText("Percentage of first time passes: ");
        jPanel5.add(jLabel7);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        jPanel6.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
        numPassedLabel.setText("0");
        jPanel6.add(numPassedLabel);

        untestedLabel.setText("0");
        jPanel6.add(untestedLabel);

        totalNumTestsLabel.setText("0");
        jPanel6.add(totalNumTestsLabel);

        numRetestsLabel.setText("0");
        jPanel6.add(numRetestsLabel);

        percentFirstTimePassesLabel.setText("0%");
        jPanel6.add(percentFirstTimePassesLabel);

        jPanel1.add(jPanel6);

        jPanel3.add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel4.setBorder(new javax.swing.border.EtchedBorder());
        saveCheckBox.setSelected(true);
        saveCheckBox.setText("Save Results for use in Revision testing.");
        jPanel4.add(saveCheckBox);

        retestButton.setText("Retest first time mistakes");
        retestButton.setToolTipText("Start a new test containing all the items that you did not pass first time.");
        retestButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                retestButtonActionPerformed(evt);
            }
        });

        jPanel4.add(retestButton);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    private void retestButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_retestButtonActionPerformed
    {//GEN-HEADEREND:event_retestButtonActionPerformed
        // Add your handling code here:
        saveResults();
        lastTest.retestUnknown();
        mainFrame.startTest(lastTest);
    }//GEN-LAST:event_retestButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_editButtonActionPerformed
    {//GEN-HEADEREND:event_editButtonActionPerformed
        // Add your handling code here:
        saveResults();
        mainFrame.editModules(null);
    }//GEN-LAST:event_editButtonActionPerformed

    private void newTestButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newTestButtonActionPerformed
    {//GEN-HEADEREND:event_newTestButtonActionPerformed
        // Add your handling code here:
        saveResults();
        mainFrame.selectTest();
    }//GEN-LAST:event_newTestButtonActionPerformed
    
    public void initialise(Test test)
    {
        titleLabel.setText(
            UserConfig.getCurrent().getUserName()
            +"'s Test Results");
        numPassedLabel.setText(Integer.toString(test.getPassCount()));
        totalNumTestsLabel.setText(Integer.toString(test.getNumTests()));
        numRetestsLabel.setText(Integer.toString(test.getNumRetests()));
        untestedLabel.setText(Integer.toString(test.getUntested()));
        int numTestsUsed = test.getNumTests() - test.getUntested();
        double fractionFirstPasses = 0;
        if (numTestsUsed > 0)
            fractionFirstPasses = (double)test.getNumFirstTimePasses() /
                                  (double)(numTestsUsed);
        DecimalFormat percentFormat = new DecimalFormat("0.0%");
        String percentString = "??";
        try
        {
            percentString = percentFormat.format(new Double(fractionFirstPasses));
        }
        catch (IllegalArgumentException e)
        {
            System.out.println(e);
        }
        percentFirstTimePassesLabel.setText(percentString);
        lastTest = test;
        saveCheckBox.setSelected(true);
        if (test.getNumFirstTimePasses() == test.getNumTests())
        {
            // all words learnt so don't offer retest
            retestButton.setEnabled(false);
        }
        else
        {
            retestButton.setEnabled(true);
        }
    }
    
    public void saveResults()
    {
        if (saveCheckBox.isSelected() && lastTest != null)
        {
            boolean saved = false;
            long testTime = new Date().getTime();
            do 
            {
                Iterator i = lastTest.getItemIterator();            
                try
                {
                    while (i.hasNext())
                    {
                        TestItem item = (TestItem)i.next();
                        boolean passStatus = item.isPassed();
                        // check that item was actually tested
                        if (item.getTestCount() > 0)
                        {
                            // only count a pass as a real pass if it was achieved 
                            // first time
                            if (item.getTestCount() > 1) passStatus = false;

                                UserConfig.getCurrent().getTestHistory()
                                    .saveResult(item, lastTest.getType(), 
                                                testTime, passStatus);

                        }
                    }
                    UserConfig.getCurrent().getTestHistory().savePermanent();
                    System.out.println("Saved results");
                    saved = true;
                }
                catch (TestHistoryStorageException thse)
                {
                    if (JOptionPane.showConfirmDialog(this, 
                        "Do you want to abort the save?\n" + thse.getMessage(), 
                        "Error Saving Test History.", 
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION)
                    {
                        break;
                    }
                }
            } while (!saved);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton newTestButton;
    private javax.swing.JLabel numPassedLabel;
    private javax.swing.JLabel numRetestsLabel;
    private javax.swing.JLabel percentFirstTimePassesLabel;
    private javax.swing.JButton retestButton;
    private javax.swing.JCheckBox saveCheckBox;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel totalNumTestsLabel;
    private javax.swing.JLabel untestedLabel;
    // End of variables declaration//GEN-END:variables
    
}
