/*
 * -----------------------------------------------------------------------
 *  File:          $Source: /home/keith/cvsroot/projects/LanguageAids/uk/co/dabsol/stribley/language/gui/VocabTablePanel.java,v $
 *  Version:       $Revision: 1.3 $
 *  Last Modified: $Date: 2004/02/20 14:11:06 $
 * -----------------------------------------------------------------------
 *  Copyright (C) 2003 Keith Stribley <jungleglacier@snc.co.uk>
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 * -----------------------------------------------------------------------
 */

package languagetest.language.gui;

import javax.swing.JTable;

import javax.swing.JScrollPane;
import languagetest.language.test.TestItem;
import languagetest.sound.AudioPlayer;
/**
 *
 * @author  Keith Stribley
 */
public class VocabTablePanel extends javax.swing.JPanel
{
    private MainFrame mainFrame = null;
    private TestItemTable table = null;
    private FindDialog findDialog = null;
    /** Creates new form VocabTablePanel */
    public VocabTablePanel(MainFrame mainFrame)
    {
        this.mainFrame = mainFrame;        
        initComponents();
        findDialog = new FindDialog(mainFrame, false, this);
    }
    
    public void initialise()
    {
        table = new TestItemTable(mainFrame.getModules(), this);
        jScrollPane.getViewport().add(table);
        // panel seems to get overdrawn initially for some strange reason
        // so force redraw - this is a hack, need to find real cause
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    private void initComponents()//GEN-BEGIN:initComponents
    {
        jScrollPane = new javax.swing.JScrollPane();
        buttonPanel = new javax.swing.JPanel();
        findButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        add(jScrollPane, java.awt.BorderLayout.CENTER);

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        findButton.setText("Find");
        findButton.setToolTipText("Search vocab");
        findButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                findButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(findButton);

        closeButton.setText("Back");
        closeButton.setToolTipText("Return to Test Selection Panel.");
        closeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                closeButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(closeButton);

        add(buttonPanel, java.awt.BorderLayout.SOUTH);

    }//GEN-END:initComponents

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_findButtonActionPerformed
    {//GEN-HEADEREND:event_findButtonActionPerformed
        // Add your handling code here:
        findDialog.setVisible(true);
    }//GEN-LAST:event_findButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeButtonActionPerformed
    {//GEN-HEADEREND:event_closeButtonActionPerformed
        // Add your handling code here:
        findDialog.setVisible(false);
        // stop audio playing
        mainFrame.getAudio().close();
        // go back to test selection screen
        mainFrame.selectTest();
        // delete table
        jScrollPane.getViewport().remove(table);
        table = null;
        
    }//GEN-LAST:event_closeButtonActionPerformed
    
    public void editItem(TestItem item)
    {
        mainFrame.editModules(item);
        jScrollPane.getViewport().remove(table);
        table = null;
    }
    
    public JTable getTable()
    {
        return table;
    }
    public JScrollPane getScrollPane()
    {
        return jScrollPane;
    }
    
    public AudioPlayer getAudio()
    {
        return mainFrame.getAudio();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton findButton;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables
    
}
